# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: '%env(APP_LOCALE)%'
    app.import_only_channels: '%env(APP_IMPORT_ONLY_CHANNELS)%'
    app.excluded_channels: '%env(APP_EXCLUDED_CHANNELS)%'
    app.import_only_user_links: '%env(APP_IMPORT_ONLY_USER_LINKS)%'
    app.slack_api.oauth_token: '%env(SLACK_OAUTH_ACCESS_TOKEN)%'
    app.slack_api.base_url: '%env(SLACK_API_BASE_URL)%'
    app.twitter_api.oauth_access_token: '%env(TWITTER_OAUTH_ACCESS_TOKEN)%'
    app.twitter_api.oauth_access_token_secret: '%env(TWITTER_OAUTH_ACCESS_TOKEN_SECRET)%'
    app.twitter_api.consumer_key: '%env(TWITTER_CONSUMER_KEY)%'
    app.twitter_api.consumer_secret: '%env(TWITTER_CONSUMER_SECRET)%'
    app.wallabag_api.base_url: '%env(WALLABAG_API_URL)%'
    app.wallabag_api.client_id: '%env(WALLABAG_CLIENT_ID)%'
    app.wallabag_api.client_secret: '%env(WALLABAG_CLIENT_SECRET)%'
    app.wallabag_api.user_username: '%env(WALLABAG_USER_USERNAME)%'
    app.wallabag_api.user_password: '%env(WALLABAG_USER_PASSWORD)%'
    app.home.slack_link: '%env(HOME_SLACK_LINK)%'
    app.home.wallabag_link: '%env(HOME_WALLABAG_LINK)%'
    app.home.displayed_days: '%env(HOME_DISPLAYED_DAYS)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    stw.import_helper.slack_users:
        class: App\Services\Slack\UsersImportHelper
        public: true
        arguments: ["@doctrine.orm.entity_manager", "%kernel.project_dir%"]

    stw.import_helper.slack_links:
        class: App\Services\Slack\LinksImportHelper
        public: true
        arguments: ["@doctrine.orm.entity_manager", "%kernel.project_dir%"]

    stw.import_helper.full_import:
        class: App\Services\Slack\FullImportHelper
        public: true
        arguments: ["@doctrine.orm.entity_manager", "%kernel.project_dir%"]
        calls:
            - [setSlackUsersImportHelper, ["@stw.import_helper.slack_users"]]
            - [setSlackLinksImportHelper, ["@stw.import_helper.slack_links"]]

    stw.import_helper.api_import:
        class: App\Services\Slack\ApiImportHelper
        public: true
        arguments:
            - '@stw.crawl_helper.slack'
            - '@stw.import_helper.slack_links'
            - '@stw.import_helper.slack_users'

    stw.crawl_helper.slack:
        class: App\Services\Slack\CrawlHelper
        public: true
        arguments:
          - '%app.slack_api.oauth_token%'
          - '%app.excluded_channels%'
          - '%app.import_only_channels%'

    stw.twitter.links_update_helper:
        class: App\Services\Twitter\LinksUpdateHelper
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            -
                oauth_access_token: '%app.twitter_api.oauth_access_token%'
                oauth_access_token_secret: '%app.twitter_api.oauth_access_token_secret%'
                consumer_key: '%app.twitter_api.consumer_key%'
                consumer_secret: '%app.twitter_api.consumer_secret%'

    stw.export_helper.wallabag:
        class: App\Services\Wallabag\ExportHelper
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            -
                api_base_url: '%app.wallabag_api.base_url%'
                client_id: '%app.wallabag_api.client_id%'
                client_secret: '%app.wallabag_api.client_secret%'
                user_username: '%app.wallabag_api.user_username%'
                user_password: '%app.wallabag_api.user_password%'

